# Generated by Django 6.0.3 on 2026-03-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('date_performed', models.DateTimeField()),
                ('inspector_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NI', 'Not Inspected'), ('SAT', 'Satisfactory'), ('MON', 'Monitor'), ('EOSL', 'Near End of Service Life'), ('MINOR', 'Minor Defect'), ('SIG', 'Significantly Deficient'), ('COS', 'Cosmetic Defect')], default='SAT', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Specific details about this finding')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectionitem')),
            ],
        ),
    ]
