# Generated by Django 6.0.3 on 2026-03-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='address',
            new_name='property_address',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='date_performed',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspector_notes',
        ),
        migrations.AddField(
            model_name='inspection',
            name='building_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inspection',
            name='date_of_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='in_attendance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_company',
            field=models.CharField(default='Your Company Name', max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_company_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_status',
            field=models.CharField(choices=[('active', 'In Progress'), ('final', 'Complete')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(default='greg', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='license_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='occupancy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='signed_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
