# Generated by Django 6.0.3 on 2026-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_rename_address_inspection_property_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionitem',
            old_name='question',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='e.g. Toilet', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Master Bathroom', max_length=200),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_status',
            field=models.CharField(choices=[('active', 'In Progress'), ('final', 'Complete')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
