# Generated by Django 6.0.3 on 2026-03-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_rename_question_inspectionitem_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='answer',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='field_type',
            field=models.CharField(choices=[('FINDING', 'Physical Item (Uses Status)'), ('QUESTION', 'Disclosure/Information (Uses Yes/No/NA)')], default='FINDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('NI', 'Not Inspected'), ('SAT', 'Satisfactory'), ('MON', 'Monitor'), ('EOSL', 'Near End of Service Life'), ('MINOR', 'Minor Defect'), ('SIG', 'Significantly Deficient'), ('COS', 'Cosmetic Defect')], max_length=10, null=True),
        ),
    ]
