# Generated by Django 6.0.3 on 2026-03-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('NI', 'Not Inspected'), ('SAT', 'Satisfactory'), ('MON', 'Monitor'), ('EOSL', 'Near End of Service Life'), ('MINOR', 'Minor Defect'), ('SIG', 'Significantly Deficient'), ('COS', 'Cosmetic Defect'), ('NOTE', 'See Notes'), ('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=10, null=True),
        ),
    ]
