# Generated by Django 6.0.3 on 2026-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_inspectionitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
