# Generated by Django 6.0.3 on 2026-03-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_profile_company_email_profile_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='field_type',
            field=models.CharField(choices=[('FINDING', 'Physical Item (Uses Status)'), ('QUESTION', 'Disclosure/Information (Uses Yes/No/NA)')], default='FINDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('NI', 'Not Inspected'), ('NDO', 'No Defects Observed'), ('MON', 'Monitor'), ('EOSL', 'Near End of Service Life'), ('MINOR', 'Minor Defect'), ('SIG', 'Significantly Deficient'), ('COS', 'Cosmetic Defect'), ('NOTE', 'See Notes'), ('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=20, null=True),
        ),
    ]
