# Generated by Django 6.0.3 on 2026-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_alter_inspectionitem_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
