# Generated by Django 6.0.3 on 2026-04-08 19:48

import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_inspection_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=inspections.models.photo_upload_path),
        ),
    ]
