services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=home_inspection_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password # Change this to something secure
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    command: ["sh", "-c", "mkdir -p /app/staticfiles && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"]
    depends_on:
      - db
    environment:
      # This tells Django to use the 'db' container instead of SQLite
      - DATABASE_URL=postgres://postgres:postgres_password@db:5432/home_inspection_db
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME}
      - SPACES_ENDPOINT_URL=${SPACES_ENDPOINT_URL}

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api/

volumes:
  postgres_data: